### ISSUE TITLE
tree.root may become invalid...again

### ISSUE THREAD

**Issue by iwburns** [iwburns/id-tree#11]
If `move_node_to_parent` is called on the root node for example like this:
```
   A
 /   \
B     C
```
`move_node_to_parent(A, B);` should result in this:
```
    B
   /
  A
   \
    C
```
Currently it _almost_ results in that, but `B`'s parent is still set to `A`, `B` is still a child of `A`, and `tree.root` is still set to `A`.

I think this can be broken down into two different issues actually:
1. calling `move_node_to_parent` on the root node (pretty sure this is the only one that affects whether or not `tree.root` is left invalid)
2. calling `move_node_to_parent(A, B)` on any pair of `Node`s where `B` is in `A`s sub-tree.

Also, I think the fundamental problem that we're having with `swap` is the same one that is described in Item 2 above.  I think this is because it's confusing to move a `Node` _down_ or _up_ the `Tree`, but it's pretty easy to move _across_ the `Tree`.

In this special case drawn out above, it shouldn't be _too_ hard to check and see if the `Node` we're moving down to (`B`) is one of `A`'s direct children and adjust the parent and child `NodeId`s accordingly.  However, it seems like it would be a bit harder to find out what to do in the general case (Item 2 above).

@Drakulix if you have any ideas on this please let me know.

**Comment by iwburns** [comment]
To solve the problem in Item 2 above, we first have to know if `B` is in `A`'s sub-tree.  If it isn't, then this is a simple _across_ the tree move.

I'm thinking the easiest way to find out if `B` is in `A`'s sub-tree is to keep checking `Node.parent()` upwards from `B` to see if we can find `A`,  If we find `A` before we reach the root, then `B` is in `A`'s sub-tree, otherwise, it isn't.  Do you see any holes in that logic @Drakulix ?

**Comment by Drakulix** [comment]
No I dont. I think we should put this logic in a separate method of `Tree`, it might come in handy for other (future) methods as well.Am 16.12.2016 3:45 nachm. schrieb Ian Burns <notifications@github.com>:To solve the problem in Item 2 above, we first have to know if B is in A's sub-tree.  If it isn't, then this is a simple across the tree move.
I'm thinking the easiest way to find out if B is in A's sub-tree is to keep checking Node.parent() upwards from B to see if we can find A,  If we find A before we reach the root, then B is in A's sub-tree, otherwise, it isn't.  Do you see any holes in that logic @Drakulix ?

**Comment by iwburns** [comment]
I'm going to take a swing at this a bit later today / possibly tonight.  If you have free time and feel like going for it feel free, just make sure you ping me here so we don't double work it.

**Comment by iwburns** [comment]
Another thought on this:  If moving/swapping two `Node`s where one is in the other's sub-tree becomes too confusing or difficult in the general case, we may have to just return an error instead of supporting that behavior.

Don't get me wrong, I would love to support that behavior, but if it's too confusing or we can't come up with a behavior that the caller would likely understand or expect, then I would rather just make it an error.

With that said, none of the errors in `NodeIdError` would really be accurate for such a situation, so we might need to add a new `NodeIdError`.  This would end up being a breaking change since Rust requires that you cover all cases in a `match`.  In addition, that type of error shouldn't really be classified as a `NodeIdError` so we might have to rename `NodeIdError` to be more general (which would also be a breaking change of course).

Again, not saying this is the direction I want to go, just putting my thoughts out there.

**Comment by iwburns** [comment]
So, now I'm not 100% sure what the behavior of this should be.
For example:
```
        A
      /   \
    B       C
   / \     / \
  D   E   F   G
 / \         / \
H   I       J   K
               / \
              L   M
```
Currently ( with the bug fixes in #14 ) `move_node_to_parent(C, K);` will result in this: 
```
        A
      /   \
    B       G
   / \     / \
  D   E   J   K
 / \         /|\
H   I       L M C
                |
                F
```
In other words, `C` and its children (excluding the child that "points to" `K`) are moved down below `K`.
But I can also see how someone might expect this:
```
        A
      /   \
    B       K
   / \     /|\
  D   E   L M C
 / \         / \
H   I       F   G
                |
                J
```
Here, `C` and all of its children (recursively down, not including `K` or its children) are moved down below `K` and `K` is then moved up to where `C` was.
A third option would be to do something like this:
```
        A                                A            
      /                                /              
    B                                B                
   / \                              / \               
  D   E       G          OR        D   E
 / \         / \                  / \
H   I       J   K                H   I           K    
               /|\                              /|\   
              L M C                            L M C  
                  |                               / \ 
                  F                              F   G
                                                     |
                                                     J
```
Here we would just not re-connect `G` (or `K` depending on the behavior) back to `C`s parent, but I'm not as big of a fan of those options.

**Comment by iwburns** [comment]
closing because of #14 being merged

**Comment by iwburns** [comment]
v0.2.8 has been pushed up to crates.io
