### ISSUE TITLE
Implement traits

### ISSUE THREAD

**Issue by starkat99** [iwburns/id-tree#67]
Implement Debug for all types, and it would be very nice if Tree implemented Clone.

**Comment by iwburns** [comment]
Thanks for opening the issue!

Sadly I'm a bit busy on other projects right now and don't have as much time to devote to this one as I'd like at the moment.  However, I would gladly review and accept a PR if you're willing to provide one.  If not that's perfectly fine, I'll just put this on my list of things to do and get to it as soon as I can.

**Comment by cecton** [comment]
That's it for Debug (was easy). Now for Tree... if I have time I will do it. @iwburns do you know how to implement it? I just call clone() recursively or you have a better plan?

**Comment by iwburns** [comment]
>just call clone() recursively

This is my initial thought, but it's very possible there is a better way to do it.  Also there may be a few snags that you might run into with something like that.

The only major thing I can think of is that you need `NodeId`s to be tied to the new `Tree` and not to the original one.  You may have to iterate over the whole tree and "insert" cloned `Node`s into the new `Tree`.

The order of operations might be a bit odd at first (parent `Node` has to exist before child `Node`s can be added), but I don't think it would be too complicated to do.

**Comment by cecton** [comment]
Maybe instead of implementing Clone we could make a `cloned()` method [like it exist for `Iter`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.cloned):

This way only the method will require that the data implements Clone which makes more sense.

**Comment by iwburns** [comment]
@cecton I believe you can have the "best of both worlds" here by implementing like this:
`impl<T> Clone for Tree<T> where T:Clone {`

I _think_ it is the "more Rust-y way" to do this instead of having to make a one-off `cloned` method.
