### ISSUE TITLE
Serializing NodeId

### ISSUE THREAD

**Issue by ixjf** [iwburns/id-tree#75]
Hi. I have a tree-like structure based on idtree which relies on the NodeIds and that I want to serialize, however NodeId is not serializable because it doesn't implement Serde's Serialize trait, even though snowflake has an optional feature for serializing ProcessUniqueId. Do you think it would be a good idea to add an optional feature to idtree that adds this support?

**Comment by iwburns** [comment]
I think that would be perfectly fine, but I'm not actually very familiar with setting up "optional feature"s like that.  I know that it can be done (obviously other libraries do it) I've just never done that myself.

Do you know (or have the time find out) how that would be accomplished?

**Comment by ixjf** [comment]
I actually had made a fork of idtree here with the changes so I could continue my work: https://github.com/ixjf/id-tree

It's basically defining a section in Cargo.toml like:

```toml
#[features]
serde_support = ["snowflake/serde_support", "serde", "serde_derive"]
```

and including serde as an optional dependency, which is only loaded if 'serde_support' is enabled, like:

```toml
#[dependencies]
...
serde = { ..., optional = true }
serde_derive = { ..., optional = true }
```

And then using `#[cfg_attr(feature = "serde_support", derive(Serialize))]` for conditional compilation of the serialization code.

My fork only really has support for serializing NodeIds, which is what I needed, but it could very well be extended, if that's a useful thing.

**Comment by iwburns** [comment]
Would you consider making a PR with those changes?

I looked at the changes you made on your fork and they seem perfectly reasonable to me.

**Comment by ixjf** [comment]
Does that include the impl Clone trait for the iterators?

**Comment by iwburns** [comment]
I'd say keep them separate, but I don't see why we shouldn't impl Clone for the iterators off the top of my head.  I'll think on that one, but I don't see any issue with it right now.

**Comment by ixjf** [comment]
I'll try to see if there's anything I'm missing for either of the changes (they were a quick fix at the time) and make a PR for each asap, then we can continue the discussion for each separately.

**Comment by iwburns** [comment]
sounds great!  and no rush at all.
