### ISSUE TITLE
traverse_* iterators should yield NodeId as well

### ISSUE THREAD

**Issue by netvl** [iwburns/id-tree#76]
Currently there is no way to obtain `NodeId`s of the nodes being traversed using the traversal iterators. Ideally, I think, these iterators should yield `(&NodeId, &Node<T>)`, which would allow to get `NodeId`s as well.

My use case is walking a subtree of a tree and collect `NodeId`s of subtree nodes for further processing, but I also need to inspect pieces of data in nodes to determine whether to collect a node or not. But currently there is no way to traverse the tree automatically (without manual descending through `Node`s), while getting `NodeId`s.

**Comment by iwburns** [comment]
I think this is probably a good move, but sadly that would be a breaking change and I'm not sure I've got the time to do a 2.0 release in the near future (there are other things I want to do with a 2.0 release as well, but I haven't had time recently to work on them).

Would it be acceptable to add new `traverse_*` methods that behave the way you describe above for now?

**Comment by iwburns** [comment]
Also, another work-around could be to use the `*_id` iterators whenever #74 get's merged.  You'd have to do an additional lookup to get the node data (which is of course not ideal), but it would probably get you what you want.

**Comment by netvl** [comment]
@iwburns that actually would be perfect for my use case, traversing nodeids works just as well. It is actually something which I've already implemented locally, it's really nice that it is now available directly in the library :)

**Comment by iwburns** [comment]
glad to hear it!  I'll close this issue for now, but feel free to re-open or open a new one as needed.
