### ISSUE TITLE
Provide a remove function, that kills the whole subtree

### ISSUE THREAD

**Issue by Drakulix** [iwburns/id-tree#9]
I think a `remove` function that recursively removes all children should also be provided as well.

**Comment by iwburns** [comment]
I agree.  I remember thinking about including this originally as well, but I can't remember why I didn't do it.

I don't mind taking this one, but if you want it feel free to go for it.

**Comment by Drakulix** [comment]
I would eventually do it, but I am not sure when.

**Comment by iwburns** [comment]
In that case, pick it up if/when you have time, but otherwise I'll get to it when I can.  No pressure to pick this one up if you don't feel like it.

**Comment by Drakulix** [comment]
Yes. I just forgot to mark the PR as fixing this.
